[build]
    command = "npm run build"
    publish = "/build"
    base = "/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/*"
    to = "https://api.thedogapi.com/v1/breeds"
    status = 200